package com.hiddenodds.trebolv2.presentation.model


class MaintenanceModel {
    var id: String = ""
    var codeNotify = ""
    var verification1 = ""
    var verification2 = ""
    var verification3 = ""
    var verification4 = ""
    var verification5 = ""
    var verification6 = ""
    var verification7 = ""
    var verification8 = ""
    var verification9 = ""
    var verification10 = ""
    var verification11 = ""
    var verification12 = ""
    var verification13 = ""
    var verification14 = ""
    var maintenance1 = ""
    var maintenance2 = ""
    var maintenance3 = ""
    var maintenance4 = ""
    var maintenance5 = ""
    var maintenance6 = ""
    var maintenance7 = ""
    var maintenance8 = ""
    var maintenance9 = ""
    var maintenance10 = ""
    var maintenance11 = ""
    var maintenance12 = ""
    var maintenance13 = ""
    var maintenance14 = ""
    var test1 = ""
    var test2 = ""
    var test3 = ""
    var test4 = ""
    var test5 = ""
    var test6 = ""
    var test7 = ""
    var test8 = ""
    var test9 = ""
    var test10 = ""
    var test11 = ""
    var test12 = ""
    var test13 = ""
    var test14 = ""
    var test15 = ""
    var test16 = ""
    var security = ""
    var documentation = ""
    var knowPrint = ""
    var nextHours = ""
    var reportTechnical = ""
}