package com.hiddenodds.trebol.presentation.model

import java.io.Serializable


class MaintenanceModel: Serializable {
    var id: String = ""
    var codeNotify = ""
    var verification1 = "V"
    var verification2 = "V"
    var verification3 = ""
    var verification4 = ""
    var verification5 = "V"
    var verification6 = ""
    var verification7 = "V"
    var verification8 = "V"
    var verification9 = "V"
    var verification10 = "V"
    var verification11 = "V"
    var verification12 = "V"
    var verification13 = "V"
    var verification14 = "V"
    var maintenance1 = ""
    var maintenance2 = ""
    var maintenance3 = "V"
    var maintenance4 = "V"
    var maintenance5 = "V"
    var maintenance6 = "V"
    var maintenance7 = "V"
    var maintenance8 = "V"
    var maintenance9 = ""
    var maintenance10 = "V"
    var maintenance11 = ""
    var maintenance12 = ""
    var maintenance13 = ""
    var maintenance14 = ""
    var test1 = "V"
    var test2 = "V"
    var test3 = "V"
    var test4 = "V"
    var test5 = ""
    var test6 = ""
    var test7 = "V"
    var test8 = "V"
    var test9 = "V"
    var test10 = "V"
    var test11 = "V"
    var test12 = "V"
    var test13 = "V"
    var test14 = "V"
    var test15 = "V"
    var test16 = "V"
    var security = "V"
    var documentation = "V"
    var knowPrint = "V"
    var nextHours = "0"
    var reportTechnical = ""
}